name: Docker Build & Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Verify package files
        run: |
          echo "Checking package.json and package-lock.json integrity..."
          if [ -f "package.json" ] && [ -f "package-lock.json" ]; then
            echo "✅ package.json and package-lock.json exist"
            echo "package.json content (first 10 lines):"
            head -10 package.json
            echo "package-lock.json size:"
            ls -la package-lock.json
            
            # Check parser-wasm files
            echo "Checking parser-wasm files..."
            if [ -f "parser-wasm/package.json" ]; then
              echo "✅ parser-wasm/package.json exists"
            else
              echo "❌ parser-wasm/package.json is missing"
              exit 1
            fi
            
            if [ -f "parser-wasm/Cargo.toml" ]; then
              echo "✅ parser-wasm/Cargo.toml exists"
            else
              echo "❌ parser-wasm/Cargo.toml is missing"
              exit 1
            fi
          else
            echo "❌ package.json or package-lock.json is missing"
            ls -la
            exit 1
          fi
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build development Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: konficurator:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=development
          # Add verbose output for debugging
          provenance: false
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}
        
      - name: Build production Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          push: false
          load: true
          tags: konficurator:prod
          cache-from: type=gha
          cache-to: type=gha,mode=max
        
      - name: List built images
        run: |
          echo "Available Docker images:"
          docker images
        
      - name: Test development container
        run: |
          echo "Starting development container test..."
          docker run -d --name konficurator-dev -p 8080:8080 konficurator:dev
          sleep 15
          echo "Testing development container endpoint..."
          curl -f http://localhost:8080/ || exit 1
          echo "Development container test successful!"
          docker logs konficurator-dev
          docker stop konficurator-dev
          docker rm konficurator-dev
        
      - name: Test production container
        run: |
          echo "Starting production container test..."
          docker run -d --name konficurator-prod -p 8081:8080 konficurator:prod
          sleep 15
          echo "Testing production container endpoint..."
          curl -f http://localhost:8081/ || exit 1
          echo "Testing gzip compression support..."
          curl -H "Accept-Encoding: gzip" -f http://localhost:8081/ || exit 1
          echo "Testing brotli compression support..."
          curl -H "Accept-Encoding: br" -f http://localhost:8081/ || exit 1
          echo "Production container test successful!"
          docker logs konficurator-prod
          docker stop konficurator-prod
          docker rm konficurator-prod
        
      - name: Check image sizes
        run: |
          echo "Docker image sizes:"
          docker images konficurator --format "table {{.Tag}}\t{{.Size}}"
          echo ""
          echo "Production image layers:"
          docker history konficurator:prod --format "table {{.CreatedBy}}\t{{.Size}}"

  docker-compose-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version
        
      - name: Test development docker-compose
        run: |
          docker-compose up -d konficurator
          sleep 15
          curl -f http://localhost:8080/ || exit 1
          docker-compose logs konficurator
          docker-compose down
        
      - name: Test production docker-compose
        run: |
          docker-compose --profile production up -d konficurator-prod
          sleep 15
          curl -f http://localhost:8080/ || exit 1
          echo "Testing compression headers..."
          curl -I -H "Accept-Encoding: gzip" http://localhost:8080/ | grep -i "content-encoding" || echo "No compression header found"
          docker-compose --profile production logs konficurator-prod
          docker-compose --profile production down
